encoding: utf-8
markdown: kramdown
highlighter: rouge

excerpt_separator: "\n\n\n"
# Outputting
permalink: /posts/:title/
paginate: 5
paginate_path: '/posts/page/:num/'
timezone: Europe/Berlin

# Handling Reading
exclude: [Gemfile, README.md]

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

collections:
  my_categories:
    output: true
    permalink: /posts/category/:name/
  my_tags:
    output: true
    permalink: /posts/tag/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project

# Custom
repository: wejendorp/dorp.io
domain: dorp.io
url: https://dorp.io
title: dorp.io
description: Personal website of Jacob Wejendorp
name: dorp
author: wejendorp
twitter:
  username: wejendorp
github:
  username: wejendorp
